image: node:latest

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

#  install node js
  - apt-get --quiet install -y build-essential
  - curl -sL https://deb.nodesource.com/setup_8.x | -E bash -
  - apt-get --quiet install -y nodejs
  - apt-get --quiet update --yes
  - npm -v
  - npm install -g npm
  - npm install -g vue-cli

stages:
  - test
  - deploy

#deploy debug
test:
  stage: test
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
    - dist/

#deploy build production
deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
    - dist/
